server:
  port: 9090

spring:
  application:
    name: serviceB
  cloud:
    config:
      enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
