server:
  port: 9090

spring:
  application:
    name: serviceB
  cloud:
    config:
      enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registryFetchIntervalSeconds: 300000
#ribbon:
#  ConnectTimeout: 1000
#  ReadTimeout: 1000
#  OkToRetryOnAllOperations: true
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 3
