server:
  port: 8761

spring:
  cloud:
    config:
      enabled: false
      profile: single

eureka:
  instance:
    hostname: localhost
    appname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: false
    registerWithEureka: false


