server:
  port: 7002

spring:
  cloud:
    config:
      enabled: false
      profile: peer2

eureka:
  instance:
    hostname: peer2
    appname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/


